version: '3.4'
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  loket:
    restart: "no"
  dashboard:
    restart: "no"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  validation:
    restart: "no"
  file:
    restart: "no"
  create-bbcdr:
    restart: "no"
  package-bbcdr:
    restart: "no"
  deliver-bbcdr:
    restart: "no"
  dbcleanup:
    restart: "no"
  export-mandaten:
    restart: "no"
  export-leidinggevenden:
    restart: "no"
  filehost:
    restart: "no"
  sink:
    restart: "no"
  berichtencentrum-email-notification:
    restart: "no"
  submission-email-notification:
    restart: "no"
  berichtencentrum-sync-with-kalliope:
    restart: "no"
  berichtencentrum-deliver-email-service:
    restart: "no"
  download-url:
    restart: "no"
  adressenregister:
    restart: "no"
  person-reconciliation:
    restart: "no"
  report-generation:
    restart: "no"
  automatic-submission:
    restart: "no"
  import-submission:
    restart: "no"
  enrich-submission:
    restart: "no"
  validate-submission:
    restart: "no"
  toezicht-flattened-form-data-generator:
    restart: "no"
  export-submissions:
    restart: "no"
  person-uri-for-social-security-number:
    restart: "no"
  loket-mandatarissen-producer:
    restart: "no"

