version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  loket:
    image: lblod/frontend-loket:0.8.0
    links:
      - identifier:backend
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.4.0
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.2.0
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.1-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/:/opt/virtuoso-scripts
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.3.0
    links:
      - virtuoso:database
    environment:
      MU_SPARQL_TIMEOUT: '300'
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:0.6.0
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    labels:
      - "logging=true"
    image: semtech/mu-cl-resources:1.17.1
    volumes:
      - ./config/resources:/config
    restart: always
    logging: *default-logging
  login:
    image: lblod/acmidm-login-service:0.2.2
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "a2c0d6ea-01b4-4f68-920b-10834a943c27"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://loket.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
    restart: always
    logging: *default-logging
  validation:
    image: semtech/mu-validation-service:0.3.0
    labels:
      - "logging=true"
    volumes:
      - ./config/validations:/config
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.0
    labels:
      - "logging=true"
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
  createreports:
    image: lblod/create-bbcdr-rapporten-service:0.4.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  packagereports:
    image: lblod/package-bbcdr-rapporten-service:0.2.4
    labels:
      - "logging=true"
    volumes:
      - ./data/files:/data/files
    environment:
      PACKAGE_CRON_PATTERN: '0 0 * * * *'
    restart: always
    logging: *default-logging
  deliverreports:
    image: lblod/deliver-bbcdr-rapporten-service:0.2.2
    volumes:
      - ./data/files:/data/files
    environment:
      PACKAGE_CRON_PATTERN: '0 0 * * * *'
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  dbcleanup:
    image: lblod/db-cleanup-service:0.2.0
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
  export:
    image: lblod/mandaten-download-generator-service:0.2.0
    links:
      - virtuoso:database
    environment:
      EXPORT_CRON_PATTERN: "0 0 4 * * *"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/system"
    volumes:
      - ./data/exports:/data/exports
      - ./config/export:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  toezichtreporting:
    image: lblod/toezicht-inzending-reporting-service:0.2.1
    volumes:
      - ./data/toezicht-reports:/data/output
    links:
      - virtuoso:database
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  filehost:
    image: nginx:1.15.2
    volumes:
      - ./config/filehost/nginx.conf:/etc/nginx/nginx.conf
      - ./config/filehost/conf.d:/etc/nginx/conf.d
      - ./data/files:/data:ro
    restart: always
    labels:
      - "logging=true"
    logging: *default-logging
