version: '3.7'
services:
  proxy:
    image: nginx:1.13
    volumes:
      - ./config/proxy:/etc/nginx/conf.d
    ports:
      - "443:443"
  mocklogin:
    image: lblod/mock-login-service:0.3.1
  loket:
    restart: "no"
  dashboard:
    restart: "no"
  identifier:
    ports:
      - "90:80"
    restart: "no"
  dispatcher:
    restart: "no"
  database:
    restart: "no"
  virtuoso:
    ports:
      - "8890:8890"
    restart: "no"
  deltanotifier:
    restart: "no"
  migrations:
    restart: "no"
  cache:
    restart: "no"
  resource:
    restart: "no"
  login:
    restart: "no"
  validation:
    restart: "no"
  file:
    restart: "no"
  create-bbcdr:
    restart: "no"
  package-bbcdr:
    restart: "no"
  deliver-bbcdr:
    restart: "no"
  dbcleanup:
    restart: "no"
  filehost:
    restart: "no"
  sink:
    restart: "no"
  berichtencentrum-email-notification:
    restart: "no"
  submission-email-notification:
    restart: "no"
  berichtencentrum-sync-with-kalliope:
    restart: "no"
  deliver-email-service:
    restart: "no"
  download-url:
    restart: "no"
  adressenregister:
    restart: "no"
  person-reconciliation:
    restart: "no"
  report-generation:
    restart: "no"
  automatic-submission:
    restart: "no"
  import-submission:
    restart: "no"
  enrich-submission:
    restart: "no"
  validate-submission:
    restart: "no"
  toezicht-flattened-form-data-generator:
    restart: "no"
  export-submissions:
    restart: "no"
  person-uri-for-social-security-number:
    restart: "no"
  sync-with-kalliope-error-notification:
    restart: "no"
  mandataris-archive:
    restart: "no"
  subsidy-applications-management:
    environment:
      VERSIONED_CONFIGURATION_WATCHER: null
    restart: "no"
  berichtencentrum-warning:
    restart: "no"
  download-url-warning:
    restart: "no"
  case-number-generator:
    restart: "no"
  subsidy-application-flow-management:
    restart: "no"
  delta-producer-report-generator:
    restart: "no"
  delta-producer-dump-file-publisher:
    restart: "no"
  delta-producer-background-jobs-initiator-leidinggevenden:
    restart: "no"
  delta-producer-publication-graph-maintainer-leidinggevenden:
    restart: "no"
  delta-producer-json-diff-file-publisher-leidinggevenden:
    restart: "no"
  delta-producer-background-jobs-initiator-mandatarissen:
    restart: "no"
  delta-producer-publication-graph-maintainer-mandatarissen:
    restart: "no"
  delta-producer-json-diff-file-publisher-mandatarissen:
    restart: "no"
  prepare-submissions-for-export:
    restart: "no"
