version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  loket:
    image: lblod/frontend-loket:0.37.0
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dashboard:
    image: lblod/frontend-dashboard:1.0.1
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  vendor-management:
    image: lblod/frontend-vendor-access-management:0.4.1
    links:
      - identifier:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  identifier:
    image: semtech/mu-identifier:1.7.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deltanotifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
      - ./config/delta:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.4
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.1
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/db/:/opt/virtuoso-scripts
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  migrations:
    image: semtech/mu-migrations-service:0.6.0
    links:
      - virtuoso:database
    environment:
      MU_SPARQL_TIMEOUT: '300'
    volumes:
      - ./config/migrations:/data/migrations
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.19.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  login:
    image: lblod/acmidm-login-service:0.8.0
    environment:
      MU_APPLICATION_AUTH_DISCOVERY_URL: "https://authenticatie-ti.vlaanderen.be/op"
      MU_APPLICATION_AUTH_CLIENT_ID: "a2c0d6ea-01b4-4f68-920b-10834a943c27"
      MU_APPLICATION_AUTH_REDIRECT_URI: "https://loket.lblod.info/authorization/callback"
      MU_APPLICATION_AUTH_CLIENT_SECRET: "secret"
      LOG_SINK_URL: "http://sink"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  validation:
    image: semtech/mu-validation-service:0.3.0
    volumes:
      - ./config/validations:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.1
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  create-bbcdr:
    image: lblod/create-bbcdr-rapporten-service:0.5.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  package-bbcdr:
    image: lblod/package-bbcdr-rapporten-service:0.3.4
    volumes:
      - ./data/files:/data/files
    environment:
      PACKAGE_CRON_PATTERN: '0 0 * * * *'
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deliver-bbcdr:
    image: lblod/deliver-bbcdr-rapporten-service:0.3.5
    volumes:
      - ./data/files:/data/files
    environment:
      PACKAGE_CRON_PATTERN: '0 0 * * * *'
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  dbcleanup:
    image: lblod/db-cleanup-service:0.3.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  export-leidinggevenden:
    image: lblod/mandaten-download-generator-service:0.3.6
    links:
      - virtuoso:database
    environment:
      EXPORT_CRON_PATTERN: "0 0 5 * * 6" # only on saturday
      EXPORT_FILE_BASE: "leidinggevenden"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/system/export-leidinggevenden"
    volumes:
      - ./data/exports/leidinggevenden:/data/exports
      - ./config/export/leidinggevenden:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  export-mandaten:
    image: lblod/mandaten-download-generator-service:0.3.6
    links:
      - virtuoso:database
    environment:
      EXPORT_CRON_PATTERN: "0 0 4 * * 6" # only on saturday
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/system/export-mandatendatabank"
    volumes:
      - ./data/exports/mandaten:/data/exports
      - ./config/export/mandaten:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  berichtencentrum-email-notification:
    image: lblod/berichtencentrum-email-notification-service:0.1.5
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  submission-email-notification:
    image: lblod/toezicht-submission-email-notification-service:0.2.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  deliver-email-service:
    image: redpencil/deliver-email-service:0.1.3
    environment:
      MAILBOX_URI: 'http://data.lblod.info/id/mailboxes/1'
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  berichtencentrum-sync-with-kalliope:
    image: lblod/berichtencentrum-sync-with-kalliope-service:0.6.5
    environment:
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
      MU_SPARQL_UPDATEPOINT: "http://database:8890/sparql"
      KALLIOPE_PS_UIT_ENDPOINT: "https://kalliope-svc-test.abb.vlaanderen.be/api/poststuk-uit"
      KALLIOPE_PS_IN_ENDPOINT: "https://kalliope-svc-test.abb.vlaanderen.be/api/poststuk-in"
      BERICHTEN_CRON_PATTERN: "*/5 * * * *"
      INZENDINGEN_CRON_PATTERN: "0 22 * * *"
      MAX_MESSAGE_AGE: 1
      MAX_SENDING_ATTEMPTS: 20
      INZENDING_BASE_URL: "https://besluiten.abb.lblod.info/supervision/submissions"
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
      MU_SPARQL_UPDATEPOINT: "http://database:8890/sparql"
    volumes:
      - ./data/files:/data/files
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  filehost:
    image: nginx:1.15.2
    volumes:
      - ./config/filehost/nginx.conf:/etc/nginx/nginx.conf
      - ./config/filehost/conf.d:/etc/nginx/conf.d
      - ./data/files:/data:ro
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  sink:
    image: nginx:1.15.2
    volumes:
      - ./config/sink/sink.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  adressenregister:
    image: lblod/adressenregister-fuzzy-search-service:0.4.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  person-reconciliation:
    image: lblod/person-reconciliation-service:0.3.0
    labels:
      - "logging=true"
    restart: 'no'
    logging: *default-logging
  report-generation:
    image: lblod/loket-report-generation-service:0.3.0
    links:
      - database:database
    volumes:
      - ./data/files:/share
      - ./config/reports:/app/reports
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  download-url:
    image: lblod/download-url-service:0.4.1
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  automatic-submission:
    image: lblod/automatic-submission-service:0.8.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  import-submission:
    image: lblod/import-submission-service:0.4.9
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  enrich-submission:
    image: lblod/enrich-submission-service:0.7.5
    environment:
      ACTIVE_FORM_FILE: "share://semantic-forms/20210208122305-forms.ttl"
    volumes:
      - ./config/semantic-forms:/share/semantic-forms
      - ./data/files/submissions:/share/submissions
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  validate-submission:
    image: lblod/validate-submission-service:0.9.0
    volumes:
      - ./config/semantic-forms:/share/semantic-forms
      - ./data/files/submissions:/share/submissions
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  toezicht-flattened-form-data-generator:
    image: lblod/toezicht-flattened-form-data-generator:0.5.0
    volumes:
      - ./data/files/submissions:/share/submissions
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  export-submissions:
    image: lblod/mandaten-download-generator-service:0.3.6
    links:
      - virtuoso:database
    environment:
      EXPORT_CRON_PATTERN: "0 0 3 * * *"
      EXPORT_FILE_BASE: "submissions"
      MU_APPLICATION_GRAPH: "http://mu.semte.ch/graphs/system/export-submissions"
    volumes:
      - ./data/exports/submissions:/data/exports
      - ./config/export/submissions:/config
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  clean-up-submission:
    image: lblod/clean-up-submission-service:0.2.0
    volumes:
      - ./data/files:/share
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  person-uri-for-social-security-number:
    image: lblod/person-uri-for-social-security-number-service:0.3.0
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  sync-with-kalliope-error-notification:
    image: lblod/sync-with-kalliope-error-notification-service:0.1.3
    environment:
      EMAIL_FOLDER: "http://data.lblod.info/id/mail-folders/2"
      EMAIL_GRAPH: "http://mu.semte.ch/graphs/system/email"
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  loket-mandatarissen-producer:
    image: lblod/loket-mandatarissen-producer:0.2.5
    environment:
      RELATIVE_FILE_PATH: "deltas/mandatarissen"
      PUBLISHER_URI: "http://data.lblod.info/services/loket-mandatarissen-producer"
    volumes:
      - ./config/producer/mandatarissen:/config
      - ./data/files:/share
    restart: always
    logging: *default-logging
  loket-leidinggevenden-producer:
    image: lblod/loket-mandatarissen-producer:0.2.5
    environment:
      RELATIVE_FILE_PATH: "deltas/leidinggevenden"
      PUBLISHER_URI: "http://data.lblod.info/services/loket-leidinggevenden-producer"
    volumes:
      - ./config/producer/leidinggevenden:/config
      - ./data/files:/share
    restart: always
    logging: *default-logging
  mandataris-archive:
    image: lblod/mandataris-archive-service:0.0.6
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  subsidy-applications-management:
    image: lblod/subsidy-applications-management-service:0.5.0-beta.1 # temporary beta version (needs testing)
    environment:
      VERSIONED_CONFIGURATION_WATCHER: "true"
      # “At every 15th minute past every hour from 8 through 18 on every day-of-week from Monday through Friday.”
      META_DATA_CRON: "0 */15 8-18 * * 1-5"
    volumes:
      - ./config/subsidy-application-management:/config
      - ./data/files/subsidies:/data
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  berichtencentrum-warning:
    image: lblod/berichtencentrum-warning-service:0.0.2
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
  download-url-warning:
    image: lblod/download-url-warning-service:0.0.2
    labels:
      - "logging=true"
    restart: always
    logging: *default-logging
